### ISSUE TITLE
State of this Project

### ISSUE THREAD

**Issue by thelooter** [nmondal/spark-11#9]
Is this Project still maintained. There haven't been any commits for a while now and several open PRs

**Comment by turing85** [comment]
Looking at the state of the project, it seems that we have some individuals that want to contribute/maintain. It would be nice to keep the project active.

**Comment by moritzfl** [comment]
There have been 5 pull requests so far and none of them have been merged.

Some are highly relevant changes such as the Jetty 12 support.

Just let us know how to proceed - I am fine with creating a fork and merging the PRs. However nobody wants the n-th fork if it is not absolutely needed ;)

**Comment by buckelieg** [comment]
+1

**Comment by nmondal** [comment]
@moritzfl we are working on Jetty 12. Also, why exactly moving to Jetty 12 would be a relevant one?

**Comment by moritzfl** [comment]
Thanks for clarifying. I didn't check the Pom.xml but relied on the documentation instead. The Readme still mentions Jetty 11. 

The move to Jetty 12 is important, because Jetty 11 will be EOL in January.

**Comment by nmondal** [comment]
@moritzfl  -- it is merged, but with a tiny issue ( Jetty 12 changes caused a test to fail ) -- which I fixed it ( in a hacky way ) 

https://github.com/nmondal/spark-11/pull/11

**Comment by nmondal** [comment]
@moritzfl  this is released now! Good job everyone!
